name: Publicar Imagem Docker na Azure

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login no ACR
        uses: docker/login-action@v3
        with:
          registry: acrfcg.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Build e push da imagem
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            acrfcg.azurecr.io/fcg-users-api:latest
            acrfcg.azurecr.io/fcg-users-api:${{ github.sha }}
          secrets: |
            nuget_token=${{ secrets.NUGET_AUTH_TOKEN }}